var chart = AmCharts.makeChart( "chartdiv", {
  "type": "serial",
  "addClassNames": true,
  "theme": "light",
  "autoMargins": false,
  "marginLeft": 90,
  "marginRight": 8,
  "marginTop": 10,
  "marginBottom": 26,
  "balloon": {
    "adjustBorderColor": false,
    "horizontalPadding": 10,
    "verticalPadding": 8,
    "color": "#ffffff"
  },

  "dataProvider": [ {
    "quarter": 2014+'Q1',
    "income": 70855232,
    "expenses": -41.23,
    "expenses2": -5.675,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
	  "quarter": 2014+'Q2',
    "income": 59551320,
    "expenses": 20.772,
	"expenses2": 71.1,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2014+'Q3',
    "income": 73088808,
    "expenses": 30.5,
    "expenses2": 50.5,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2014+'Q4',
    "income": 66843312,
    "expenses": 34.9,
    "expenses2": 88.9,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
	  "quarter": 2015+'Q1',
    "income": 73575776,
    "expenses": 21.1,
	"expenses2": 81.1,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2015+'Q2',
    "income": 81390752,
    "expenses": 30.5,
    "expenses2": 60.5,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
	  "quarter": 2015+'Q3',
    "income": 76391664,
    "expenses": 21.1,
	"expenses2": 51.1,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2015+'Q4',
    "income": 94311424,
    "expenses": 30.5,
    "expenses2": 80.5,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2016+'Q1',
    "income": 89702808,
    "expenses": 34.9,
    "expenses2": 72.9,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2016+'Q2',
    "income": 91085320,
    "expenses": 31.1,
    "expenses2": 60.1,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2016+'Q3',
    "income": 93029912,
    "expenses": 28.2,
    "expenses2": 90.2,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675
  }, {
    "quarter": 2016+'Q4',
    "income": 78112016,
    "expenses": 32.9,
    "expenses2": 51.9,
	"expenses3": -5.675,
	"expenses4": -5.675,
	"expenses5": -5.675,
    "alpha": 1,
    "additional": "(projection)"
  } ],
  "valueAxes": [ {
	"stackType": "100%",
    "axisAlpha": 0,
    "position": "left"
  } ],
  "startDuration": 1,
  "graphs": [ {
    "alphaField": "alpha",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>[[value]]</span> [[additional]]</span>",
    "fillAlphas": 1,
    "title": "季營收",
    "type": "column",
    "valueField": "income",
    "dashLengthField": "dashLengthColumn"
  }, {
    "id": "graph2",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>([[percents]]%)</span>",
    "bullet": "round",
    "lineThickness": 3,
    "bulletSize": 7,
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "useLineColorForBulletBorder": true,
    "bulletBorderThickness": 3,
    "fillAlphas": 0,
    "lineAlpha": 1,
    "title": "毛利率%",
    "valueField": "expenses",
    "dashLengthField": "dashLengthLine"
  }, {
    "id": "graph3",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>([[percents]]%)</span>",
    "bullet": "round",
    "lineThickness": 3,
    "bulletSize": 7,
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "useLineColorForBulletBorder": true,
    "bulletBorderThickness": 3,
    "fillAlphas": 0,
    "lineAlpha": 1,
    "title": "營業利益率%",
    "valueField": "expenses2",
    "dashLengthField": "dashLengthLine"
  }, {
    "id": "graph4",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>([[percents]]%)</span>",
    "bullet": "round",
    "lineThickness": 3,
    "bulletSize": 7,
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "useLineColorForBulletBorder": true,
    "bulletBorderThickness": 3,
    "fillAlphas": 0,
    "lineAlpha": 1,
    "title": "稅前純益率%",
    "valueField": "expenses3",
    "dashLengthField": "dashLengthLine"
  }, {
    "id": "graph5",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>([[percents]]%)</span>",
    "bullet": "round",
    "lineThickness": 3,
    "bulletSize": 7,
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "useLineColorForBulletBorder": true,
    "bulletBorderThickness": 3,
    "fillAlphas": 0,
    "lineAlpha": 1,
    "title": "稅後純益成長率%",
    "valueField": "expenses4",
    "dashLengthField": "dashLengthLine"
  }, {
    "id": "graph6",
    "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>[[value]]</span> [[additional]]</span>",
    "bullet": "round",
    "lineThickness": 3,
    "bulletSize": 7,
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "useLineColorForBulletBorder": true,
    "bulletBorderThickness": 3,
    "fillAlphas": 0,
    "lineAlpha": 1,
    "title": "股價(季底)",
    "valueField": "expenses5",
    "dashLengthField": "dashLengthLine"
  }
   ],
  "categoryField": "quarter",
  "categoryAxis": {
    "gridPosition": "start",
    "axisAlpha": 0,
    "tickLength": 0
  },
  //圖文下方解說
  "legend": {
    "bulletType": "round",
    "equalWidths": false,
    "valueWidth": 120,
    "useGraphSettings": true,
    //"color": "#FFFFFF"
	//圖文下方解說END
  },
  "export": {
    "enabled": true
  }
} );
